[package]
name = "ob-pub"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
clap = "4.3.21"
chrono = "0.4"
chrono-tz = "0.6"
